import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { LoginComponent } from './login/login.component';
import { DashboardComponent } from './dashboard/dashboard.component';
import { ReportComponent } from './report/report.component';
import { PlaceholderComponent } from './placeholder/placeholder.component';
import { MyProfileComponent } from './my-profile/my-profile.component';
import { PatientsComponent } from './patients/patients.component';
import { ClientsComponent } from './clients/clients.component';
import { DrugsComponent } from './drugs/drugs.component';
import { InsurancesComponent } from './insurances/insurances.component';
import { ManufacturerComponent } from './manufacturer/manufacturer.component';
import { ProvidersComponent } from './providers/providers.component';
import { UsersComponent } from './users/users.component';

export const routes: Routes = [
	{ path: '', component: HomeComponent },
	{ path: 'login', component: LoginComponent },
	{ path: 'dashboard', component: DashboardComponent },
	{ path: 'reports', component: ReportComponent },
	{ path: 'my-profile', component: MyProfileComponent },
	{ path: 'patients', component: PatientsComponent },
	{ path: 'call-list', component: PlaceholderComponent },
	{ path: 'list', component: PlaceholderComponent },
	{ path: 'batch-payment', component: PlaceholderComponent },
	{ path: 'invoices', component: PlaceholderComponent },
	{ path: 'users', component: UsersComponent },
	{ path: 'clients', component: ClientsComponent },
	{ path: 'drugs', component: DrugsComponent },
	{ path: 'insurances', component: InsurancesComponent },
	{ path: 'manufacturer', component: ManufacturerComponent },
	{ path: 'providers', component: ProvidersComponent },
	{ path: '**', redirectTo: '' }
];
